"
Mathemagics is a symbolic algebra package written in Pharo Smalltalk.

The purpose is to allow Smalltalk write mathematical expression following Math's precedence, allow simplification, evaluation, and other operations, while supporting integration from and to Smalltalk.

Contact:
	Gustavo Pistoia.
	See help class for more information.
"
Class {
	#name : #ManifestMathemagicsCore,
	#superclass : #PackageManifest,
	#category : #'Mathemagics-Core-Manifest'
}
